# Model Overview

The Kuehn et al. (2024) ("KEA24") fault displacement amplitude model ("FDM")
predicts a probability distribution for the total discrete net displacement 
across simple and complex fault surface ruptures. We refer to this as 
*aggregated displacement* and it includes the summed displacement across 
(sub)parallel principal and distributed faults. The model *does not* provide 
partitioning or deaggregation of the displacement onto principal or distributed 
sources. The aggregated displacement is conditional on *principal rupture* 
occurring; in other words, the aggregated displacement assumes the occurrence of 
non-zero principal displacement. The model can be used with the PFDHA earthquake 
approach methodology in Youngs et al. (2003) and can be combined with any 
appropriate model for the conditional probability of principal surface rupture.

The KEA22 is an empirical model that uses a Box-Cox transformation where the
transformed displacement $Y$ is defined as

$$Y = \frac{D^\lambda - 1}{\lambda}$$

where $D$ is the aggregated displacement in meters and $\lambda$ is a transformation
parameter estimated in the modeling. 

Data transformations are commonly used to fulfill assumptions in statistical 
modeling and/or to simplify the modeling. For example, the logarithmic 
transformation $Y=ln(y)$ is widely used in ground motion modeling. Kuehn et al. 
(2024) found that the aggregated fault displacement data were not log-normally 
distributed and therefore applied a Box-Cox transformation on the aggregated 
displacement dataset to produce a model dataset thatwas approximately normally 
distributed.

The transformed displacement assumed to follow a normal distribution, 
$Y\sim N(\mu, \sigma)$,which is convenient for fault displacement hazard calculations. 
Earthquake moment magnitude $\textbf{M}$ and normalized location along the rupture 
length $U_*$ (also known as $\frac{x}{L}$or $\frac{l}{L}$ in other models) are 
used as predictor variables. 

Between-event terms were modeled as random effects and used in the development
of the median prediction ($\mu$) model. The total aleatory variability ($\sigma$)
is separated into magnitude- and location-dependent components, and the functional 
forms vary with style of faulting. The functional form for the median prediction 
($\mu$) is independent of style. Model coefficients for both the median and standard 
deviation predictions are based on style. 

The model was developed using Bayesian regression, which means posterior distributions 
provide the final estimate of the model coefficients. This is different than most 
other models, which use maximum likelihood estimation to develop point estimates of 
the model coefficients, and is discussed in more detail in **Model Implementation**. 

Finally, the model predicts an asymmetrical slip profile, such that the profile peak 
occurs at $U_* \le 0.5$, and therefore the full normalized rupture length (i.e., 
$U_* ~\epsilon~ [0, 1]$) should be used. This is different that most other models, 
which use a folded rupture length (i.e., $\frac{x}{L} ~\epsilon~ [0, 0.5]$), and it 
is important to note that a folded rupture length should *not* be used in the KEA24 
FDM because both the median and standard deviation predictions vary along the full 
rupture length.






